stages:
  - build
  - test
  - publish


build_binary:
  stage: build
  tags:
    - x86_64
  image: registry.gitlab.com/modioab/base-image/fedora-28/container:master
  script:
    - make project/hello
  artifacts:
      paths:
          - project/hello
      expire_in: 1 week


test_hello:
  stage: test
  tags:
    - x86_64
  image: ubuntu:latest
  script:
    - bash -x hello.sh


container:
  stage: publish
  tags:
      - buildah
      - x86_64
  image: registry.gitlab.com/modioab/base-image/fedora-28/container:master
  before_script:
      - make login
  dependencies:
      - build_binary
  script:
      - make -C project build-publish
