IMAGE_REPO = registry.gitlab.com/spindel/example-container-small/example
IMAGE_TAG_PREFIX = something

FEDORA_ROOT_ARCHIVE = rootfs.tar
IMAGE_FILES = $(FEDORA_ROOT_ARCHIVE)
FEDORA_ROOT_PACKAGES = bash
FEDORA_ROOT_PACKAGES += openssh-clients

include ../build.mk
